import { requireRole } from "@/lib/auth/session";
import { listCompanies, listFormats, listGoals, listPillars, listPlatforms } from "@/features/master-data/repository";
import { saveCompanyAction, saveFormatAction, saveGoalAction, savePillarAction, savePlatformAction } from "@/features/master-data/actions";
import { PageHeader } from "@/components/shared/PageHeader";

type Item = { id:string; name:string; isActive:boolean; order:number; description?:string; shortName?:string };

function State({active}:{active:boolean}) { return <span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{active?"Aktif":"Nonaktif"}</span>; }

function MasterSection({title,description,items,canManage,action,kind}:{title:string;description:string;items:Item[];canManage:boolean;action:(formData:FormData)=>Promise<void>;kind:"company"|"descriptive"|"simple"}) {
  return <section className="card-pad"><h2 className="section-title">{title}</h2><p className="muted mt-1">{description}</p><div className="mt-4 space-y-2">{items.map((item)=>canManage?<details key={item.id} className="rounded-xl border border-slate-100 px-3 py-3"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><p className="text-sm font-semibold">{item.name}</p><State active={item.isActive}/></summary><form action={action} className="mt-4 space-y-2 border-t border-slate-100 pt-3"><input type="hidden" name="id" value={item.id}/><label className="label">Nama</label><input className="field" name="name" required defaultValue={item.name}/>{kind==="company"?<><label className="label">Nama singkat</label><input className="field" name="shortName" defaultValue={item.shortName} placeholder="Contoh: Lunar"/></>:null}{kind==="descriptive"?<><label className="label">Keterangan</label><textarea className="field" name="description" defaultValue={item.description} placeholder="Opsional"/></>:null}<label className="label">Urutan tampil</label><input className="field" inputMode="numeric" name="order" defaultValue={item.order}/><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" name="isActive" defaultChecked={item.isActive}/> Bisa dipilih</label><button className="btn-secondary w-full">Simpan perubahan</button></form></details>:<div key={item.id} className="rounded-xl border border-slate-100 px-3 py-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{item.name}</p><State active={item.isActive}/></div></div>)}</div>{canManage?<form action={action} className="mt-4 space-y-2 border-t border-slate-100 pt-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Tambah baru</p><input className="field" name="name" required placeholder={`Nama ${title.toLowerCase()}`}/>{kind==="company"?<input className="field" name="shortName" placeholder="Nama singkat (opsional)"/>:null}{kind==="descriptive"?<textarea className="field" name="description" placeholder="Keterangan singkat (opsional)"/>:null}<input className="field" inputMode="numeric" name="order" placeholder="Urutan tampil"/><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" name="isActive" defaultChecked/> Bisa dipilih</label><button className="btn-secondary w-full">Tambah</button></form>:null}</section>;
}

export default async function SettingsPage() {
  await requireRole(["ADMIN"]);
  const [companies,pillars,goals,platforms,formats]=await Promise.all([listCompanies(),listPillars(),listGoals(),listPlatforms(),listFormats()]);
  const canManage=true;
  return <div className="page-wrap"><PageHeader eyebrow="Data pendukung" title="Pengaturan" description="Atur perusahaan dan pilihan sederhana yang dipakai saat membuat konten."/><div className="grid gap-5 xl:grid-cols-2"><MasterSection title="Perusahaan" description="Brand atau perusahaan yang media sosialnya dikelola tim Media, misalnya Nexty Labs, Lunar Konstruksi, dan Yuk Jadi Legal." items={companies} canManage={canManage} action={saveCompanyAction} kind="company"/><MasterSection title="Kategori Konten" description="Contoh: Edukasi, Promosi, Portofolio, Testimoni, atau Hiburan." items={pillars} canManage={canManage} action={savePillarAction} kind="descriptive"/><MasterSection title="Tujuan Konten" description="Contoh: Awareness, Consideration, Conversation, atau Conversion." items={goals} canManage={canManage} action={saveGoalAction} kind="descriptive"/><MasterSection title="Platform" description="Tempat konten akan tayang. Satu konten bisa memilih beberapa platform." items={platforms} canManage={canManage} action={savePlatformAction} kind="simple"/><MasterSection title="Jenis Konten" description="Contoh: Feed, Carousel, Reels, Story, atau Video." items={formats} canManage={canManage} action={saveFormatAction} kind="simple"/></div></div>;
}
